# Usar una imagen base de Python
FROM python:3.11-slim
# Establecer un directorio de trabajo
WORKDIR /app
# Copiar el archivo client.py en la imagen
COPY client.py ./client.py
# Ejecutar el script client.py cuando se inicie el contenedor
CMD ["python", "./client.py"]